@BASE_URL = http://localhost:3000/api


get {{BASE_URL}}/users
###



POST {{BASE_URL}}/users
Content-Type: application/json

{
 
  "isim":"ssdsds ",
  "email": "emrealtunbilekdsds21s0m",  
  "userName": "emrealtunbilek2101",
  "sifre" : "123456"
}

###
PATCH  {{BASE_URL}}/users/61ef2c19c2efb3be3102bdc6
Content-Type: application/json

{
 
  "id" : "61ef2c19 ",
  "userName": "emrealtunbilek2201"
}
###
DELETE  {{BASE_URL}}/users/61ec8f5caecd5544d5c1e3fb
Content-Type: application/json