GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

{ 

  
  "isim":"sait",
  "yas": 32


}
###
POST http://localhost:3000/
Content-Type: application/x-www-form-urlencoded
isim=emre&yas=32