@BASE_URL = http://localhost:3000/api


get {{BASE_URL}}/users
###



POST {{BASE_URL}}/users
Content-Type: application/json

{
 
  "isim":"sait",
  "email": "sait@gmail.com",  
  "userName": "emssddb",
  "sifre" : "2101133"
}
###



POST {{BASE_URL}}/users/giris
Content-Type: application/json

{
 
  
  "email": "sait@gmail.com",  
  "sifre" : "2101133"
}

###
PATCH  {{BASE_URL}}/users/61f004c23e025b19efc09b2c
Content-Type: application/json

{
 
  
  "sifre": "2101133sd"
}
###
DELETE  {{BASE_URL}}/users/61f0150784a53997976bb2b3
Content-Type: application/json



61ef256a135b07be98935f2d